import React from 'react';
import { motion } from 'framer-motion';
import { FileText, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const TermsOfService: React.FC = () => {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-[#0a050c] text-white selection:bg-[#ce2bee]/30 pb-20">
            {/* Dynamic Background */}
            <div className="fixed inset-0 overflow-hidden pointer-events-none">
                <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-[#ce2bee]/10 blur-[120px] rounded-full" />
                <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-[#422348]/20 blur-[120px] rounded-full" />
            </div>

            <div className="relative z-10 w-full max-w-4xl mx-auto px-6 py-12 sm:py-20">
                <button
                    onClick={() => navigate('/')}
                    className="flex items-center gap-2 text-[#c092c9] hover:text-white transition-colors mb-12 group"
                >
                    <ArrowLeft size={20} className="group-hover:-translate-x-1 transition-transform" />
                    <span className="font-bold uppercase tracking-widest text-xs">Back to Home</span>
                </button>

                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="space-y-12"
                >
                    <div className="flex items-center gap-4">
                        <div className="w-16 h-16 bg-[#ce2bee] rounded-2xl flex items-center justify-center shadow-lg shadow-[#ce2bee]/20">
                            <FileText className="text-white" size={32} />
                        </div>
                        <div>
                            <h1 className="text-4xl sm:text-5xl font-black tracking-tight bg-gradient-to-r from-white to-[#c092c9] bg-clip-text text-transparent">
                                Terms of Service
                            </h1>
                            <p className="text-[#c092c9] font-medium uppercase tracking-widest text-sm mt-2">Last Updated: February 2026</p>
                        </div>
                    </div>

                    <div className="prose prose-invert max-w-none space-y-8 text-[#c092c9] leading-relaxed">
                        <section className="bg-[#1f1122]/30 border border-white/5 p-8 rounded-[32px]">
                            <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
                            <p>
                                By accessing and using AIO REXPO QR, you agree to comply with and be bound by these Terms of Service. If you do not agree, please refrain from using our platform.
                            </p>
                        </section>

                        <section className="bg-[#1f1122]/30 border border-white/5 p-8 rounded-[32px]">
                            <h2 className="text-2xl font-bold text-white mb-4">2. Description of Service</h2>
                            <p>
                                AIO REXPO QR provides users with tools to generate QR codes and create custom Bio Pages. This service is provided "as is" and is free for both personal and commercial use.
                            </p>
                        </section>

                        <section className="bg-[#1f1122]/30 border border-white/5 p-8 rounded-[32px]">
                            <h2 className="text-2xl font-bold text-white mb-4">3. User Responsibilities</h2>
                            <p>
                                Users are responsible for the content linked through the QR codes generated on this site. You agree not to use the service for:
                            </p>
                            <ul className="list-disc pl-6 space-y-2 mt-4">
                                <li>Phishing, malware, or illegal activities.</li>
                                <li>Linking to offensive or harmful content.</li>
                                <li>Spam or excessive automation that hurts our infrastructure.</li>
                            </ul>
                        </section>

                        <section className="bg-[#1f1122]/30 border border-white/5 p-8 rounded-[32px]">
                            <h2 className="text-2xl font-bold text-white mb-4">4. Limitation of Liability</h2>
                            <p>
                                Rexplore Technologies and its creators are not liable for any damages resulting from the use or inability to use the service, or from content generated by users.
                            </p>
                        </section>

                        <section className="bg-[#1f1122]/30 border border-white/5 p-8 rounded-[32px]">
                            <h2 className="text-2xl font-bold text-white mb-4">5. Modifications</h2>
                            <p>
                                We reserve the right to modify these terms at any time. Your continued use of the platform after changes are posted constitutes acceptance of the new terms.
                            </p>
                        </section>
                    </div>
                </motion.div>
            </div>
        </div>
    );
};

export default TermsOfService;
